### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by QuinnBast**
# Description

This update includes fixes to the automated builds and documentation releases so that any accepted pull requests that go to master will automatically run automated tests, run a build, and update the documentation.

# Versioning

Previous Version: v0.1.1
Next Version Number: v0.1.1

 - [ ] I have updated the README to reflect the new version number
 - [ ] When I publish a release I will append the version number to the dll's name

# Type of change

### CLI
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] New dependencies/packages

### Core
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] New dependencies/packages

# Testing

- [ ] I have created automated tests for any new features
- [ ] All automated tests pass
- [X] I have performed manual tests

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code according to C# standards
- [ ] I have made corresponding changes to the README (if required)
- [ ] I have added/updated articles in the documentation
- [ ] My changes generate no new warnings

# Questions / Discussion

### CODE REVIEW

**Comment by griendt** [comment]
The goal of the PR is clear but is there any way we can verify that it works as intended? Not sure how to go about reviewing this thing other than to just merge and see how it works :D

**Comment by QuinnBast** [comment]
> The goal of the PR is clear but is there any way we can verify that it works as intended? Not sure how to go about reviewing this thing other than to just merge and see how it works :D

If you checkout commit 4157af8 and view [the github actions file at that commit](https://github.com/Subterfuge-Revived/Remake-Core/blob/4157af8cf81a254f285be246d9a6881d2a4f83fc/.github/workflows/DeployRelease.yml) you can see that I have the workflow triggering on pushes to this branch with:

```yaml
on:
  push:
    branches: [ master, github-actions ]
```

and you can see the [workflows were successful on that commit](https://github.com/Subterfuge-Revived/Remake-Core/runs/654831446) as well. In the commit after 4157af8 I removed the `on push` action and made it trigger only on master.

**Comment by griendt** [comment]
I see that the job passes, and _almost_ everything looks perfect...

... except the deploy script. `GITHUB_SHA` is a magic variable in the CI/CD pipeline (I'm assuming) but it seems it does not get resolved properly during the deploy step. [The tag of the release is actually called GITHUB_SHA](https://github.com/Subterfuge-Revived/Remake-Core/releases/tag/GITHUB_SHA).

If you find a way to patch that it's good to go!

**Comment by griendt** [comment]
Actually, I'm a little confused, for that link refers to a release created weeks ago.

However, I found it as I was looking through the deploy job. Check the step "GH Release". It seems to use "GITHUB_SHA" as an actual string. Please correct me if I'm mistaken.

**Comment by QuinnBast** [comment]
Yep you are completely right. I solved that in 6043b44 you can see line 88, I forgot to add the `{{ }}` around the `GITHUB_SHA` in the previous commit so it used the text “GITHUB_SHA” for the release (which I later renamed to v0.1.1) instead of the actual SHA. Though my fix didn’t get tested because in that same commit I made the workflow only run on master. I can change it to run on pushes to this branch to verify if you’d like

**Comment by griendt** [comment]
Nah, doing that is a little overkill 😄 Looks good like this!

**Pull request merged**
